### ISSUE TITLE
Redirect CNAME to another one

### ISSUE THREAD

**Issue by 70nyIT** [CreateInCloud/webflow-aws#12]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I may want a CNAME to be just a redirect to another CNAME. Allow a user to configure .yaml file so that certain CNAMEs are just redirects. Idea

```
CNAMEs:
  - "example.com"
  - "old.example.com"
  - "www.example.com"
CNAMEs_redirect:
  - from:
      - example.com
      - old.example.com
    to:
      - www.example.com
```

**Describe alternatives you've considered**
Not yet considered

**Additional context**
-
